### ISSUE TITLE
question about the usage

### ISSUE THREAD

**Issue by amiltonwong** [pqhieu/torch3d#1]
Hi, @pqhieu ,

Your package `torch3d` looks very promising. If I want to try it for training and testing some dataset. Are the corresponding codes ready or not?

THX!

**Comment by pqhieu** [comment]
Hi @amiltonwong,

Thank you for your interest. The current code is usable.
I have released 0.1.0 version on PyPi, you can install it with: `pip install torch3d`.

For training and testing, take a look at the accompanied repository [`sota3d`](https://github.com/pqhieu/sota3d).
