### ISSUE TITLE
PointConv Model

### ISSUE THREAD

**Issue by ttaa9** [pqhieu/torch3d#12]
Hello,

Firstly, thanks for this repo. It would be great to have model architectures for 3D data in a lightweight repo like this!

I noticed you put PointConv in the **models** section of the readme, but there isn't a model present under `torch3d/models`. I did see the layer under `nn`, but do you plan to add a full-fledged model as well?

**Comment by pqhieu** [comment]
Thanks for the suggestion. It's definitely in my plan to implement the full model.
