### ISSUE TITLE
Question: difference with `torch-geometric`

### ISSUE THREAD

**Issue by erinaldi** [pqhieu/torch3d#3]
What are the major characteristic differences between `torch3d` and `torch-geometric` [https://pytorch-geometric.readthedocs.io/](https://pytorch-geometric.readthedocs.io/)?
They implement very similar structures, based on `pytorch`, with the addition of graph and geometric learning in `torch-geometric`.

Thank you for your help.

**Comment by pqhieu** [comment]
Thanks for your interest.

The main difference between `torch3d` and `torch-geometric` is the domain. As I understand, while `torch-geometric` has support for some operators to implement 3D deep learning models (PointNet++, PointCNN, ..), it's not the main focus of their package. On the other hand, `torch3d` takes a similar approach to the `torchvision` package, where you can get vanilla 3D deep learning models from their original papers readily implemented.

My future plan is to focus more on the state-of-the-art models for different 3D deep learning tasks (classification, segmentation, detection, ...).

Hope this answers your question.

**Comment by erinaldi** [comment]
Thank you for the detailed response.
I really appreciate your work.
As far as I understand, the domain of `torch-geometric` is geometric learning and it can be applied to 3D mesh/point cloud data by building a graph structure for those data representations. It includes all the benchmarks that you also include in `torch3d`. 

I can see how `torch3d` would be more like `torchvision` in the sense of providing API building blocks for specific 3D deep learning tasks. This is also what I am working on and I will try to contribute if that's ok!

Looking forward to new SoTA implementations.
