### ISSUE TITLE
install torch3d version 0.2 error

### ISSUE THREAD

**Issue by amiltonwong** [pqhieu/torch3d#4]
Hi, @pqhieu ,

According to your recent updates, I install torch3d version 0.2 from source. However, I got the build error. The error log details: [log](https://gist.github.com/amiltonwong/c7b75d453b8501dedff83493abd521bd)

Could you give some hints to solve this issue? Previously, I could install torch3d version 0.1 under the same environment configuration (pytorch 1.2.0).

THX!

**Comment by pqhieu** [comment]
Hi @amiltonwong,

Could you change this line https://github.com/pqhieu/torch3d/blob/f1fb19460183c0441f09dde94bac313c1df11424/torch3d/csrc/cuda/cuda.h#L3
to
```c++
#include <torch/types.h>
```
and reinstall again?

Maybe [this issue](https://github.com/pytorch/extension-cpp/issues/35) is also relevant to yours.

Please let me know if the fix works, I will update the master branch afterwards.

**Comment by amiltonwong** [comment]
@pqhieu , Yes, it works after following your suggestion.
