### ISSUE TITLE
hello.

### ISSUE THREAD

**Issue by saharahmadisohraviyeh** [pqhieu/torch3d#5]
Why don't you use stn for input and for fetcher?

**Comment by saharahmadisohraviyeh** [comment]
Why don't you use stn for input and for fetcher?

**Comment by saharahmadisohraviyeh** [comment]
Why don't you use stn for input and for feature?

**Comment by pqhieu** [comment]
In practice, the point clouds are usually aligned so you don't need to use STN. It also can slow the training considerably.

**Comment by saharahmadisohraviyeh** [comment]
Hi pqhieu!
I have a problem,when I run the visualize function in google colab,runtimes restart and my code doesn't run properly and give error :"Your session crashed for an unknown reason. View runtime logs".
I search for more information about pyvista but I can't find more useful information about my problem with googlecolab.
thanks.

**Comment by pqhieu** [comment]
Can you comment out the visualization code and try to run again?
