### ISSUE TITLE
PointNet Segmentation example

### ISSUE THREAD

**Issue by MBrandt-NASA** [pqhieu/torch3d#9]
Hi,

Many thanks for creating and sharing Torch3D!  It's really great!  I loved the ModelNet40 example -- it ran perfectly.

I would love to see a full PointNet Segmentation example, similar to the ModelNet40 example you have -- i.e. a beginner segmentation example, fully worked out.

I'm trying to adapt my own data set to use your PointNet segmentation code, but I don't see an example of the evaluate() function, etc.

Any tips for how to use our own data to do segmentation with Torch3D would be helpful!

Thanks. 😄

**Comment by pqhieu** [comment]
Thank you for your interests. Yes, a segmentation example is definitely on my roadmap.

In general, a segmentation example is very similar to a classification one, but you need to return the labels for every points in your custom dataset. I also suggest that you get familiar with PyTorch and its tutorial first if you haven't.

**Tips**: `metrics.Accuracy` also works in segmentation task. You can also use `metrics.IoU` for evaluation.

**Comment by MBrandt-NASA** [comment]
Ok great... I look forward to that example 🙂.  Thanks for the tips!
